[package]
name = "qr-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "3.2.1"
opener = "0.6.1"
qrcode-generator = "4.1.9"
